server:
  port: 8051

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/hehe-190/springlive-config
          clone-on-start: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      #defaultZone: http://${DOCKER_HOST:localhost}:8050/eureka
      #defaultZone: http://host.docker.internal:8050/eureka
      #defaultZone: ${EUREKA_SERVER:http://:localhost:8050}/eureka
      defaultZone: http://${SERVER_URL:localhost}:8050/eureka





